### ISSUE TITLE
Border + Transparency not applying in group chat member list

### ISSUE THREAD

**Issue by HawksAreNeat** [discord-addons/discord-addons#12]
Border + Transparency not applying in group chat member list 
![image](https://user-images.githubusercontent.com/54047268/141692821-0d306483-28e7-49f2-9756-eb46dc56f0f7.png)

would it be possible to get rounded corners on discord when using windows 11?

**Comment by mila684** [comment]
I don't have this issue with my Discord, try verifying your code or redownload the theme from [here](https://betterdiscord.app/theme/Opera%20GX%20Gaming%20Theme).
Also, rounded borders when using windows 11 are useless because it hides them, and the window is already rounded when not maximized. And lines should not be rounded with this theme.

**Comment by HawksAreNeat** [comment]
I redownloaded the theme. Reinstalled discord and bd but it's still happening when transparency is enabled and I'm looking at a group chat

**Comment by mila684** [comment]
Join the server then, you can easily find the invite from theme settings
